import {
  CertificationItem,
  EducationItem,
  ExperienceItem,
  Project,
  Service,
  SkillData,
  Testimonial,
} from '../types';
import thumb1 from '../assets/2.png';
import thumb2 from '../assets/3.png';
import thumb3 from '../assets/4.png';
import thumb4 from '../assets/5.png';
import thumb5 from '../assets/6.png';
import thumb6 from '../assets/7.png';

export const PROJECTS: Project[] = [
  {
    id: 18,
    title: 'Motion Graphics Intro - Africa TV',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://drive.google.com/file/d/1DWDcOEcAn6dcxr2rdR-pzP9rLu5xOgA8/preview',
    client: 'Africa TV',
    description: 'Broadcast intro with animated branding and kinetic type.',
    tools: ['Adobe After Effects'],
  },
  {
    id: 19,
    title: 'Motion Graphics Outro - Africa TV',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://drive.google.com/file/d/1c-ipQ1yufCenzIrUhZEd5BPPex2BIYlw/preview',
    client: 'Africa TV',
    description: 'Outro animation with smooth logo resolve and lower-thirds style.',
    tools: ['Adobe After Effects'],
  },
  {
    id: 20,
    title: 'Motion Graphics Bumper - Africa TV',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://drive.google.com/file/d/1k2aqxIfFwTCBav40ix2IZ0tFxh8WNGXQ/preview',
    client: 'Africa TV',
    description: 'Short bumper focusing on timing and energetic transitions.',
    tools: ['Adobe After Effects'],
  },
  {
    id: 21,
    title: 'Motion Graphics Stinger - Africa TV',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://drive.google.com/file/d/1K22yYBWoKpnMHLY4rOubx5ZIfk3KSpmm/preview',
    client: 'Africa TV',
    description: 'Stinger animation with bold colors and logo accent.',
    tools: ['Adobe After Effects'],
  },
  {
    id: 22,
    title: 'Motion Graphics Package - Clip 1',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://drive.google.com/file/d/1Dqa3aIXENsFdgOVlRVK04wqI68g4QP_7/preview',
    client: 'Africa TV',
    description: 'Animated graphics package tailored for broadcast intros.',
    tools: ['Adobe After Effects'],
  },
  {
    id: 23,
    title: 'Motion Graphics Package - Clip 2',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://drive.google.com/file/d/1XlI47LzI-1JQ5KTzXPOIJA4WNejpWCQa/preview',
    client: 'Africa TV',
    description: 'Lower-third and transition variant with kinetic typography.',
    tools: ['Adobe After Effects'],
  },
  {
    id: 24,
    title: 'Motion Graphics Package - Clip 3',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://drive.google.com/file/d/1ftYWLF1k1xj6ETf3WDS3UCtYN-PIJ5W0/preview',
    client: 'Africa TV',
    description: 'Outro-ready piece with clean logo resolve and motion accents.',
    tools: ['Adobe After Effects'],
  },
  {
    id: 14,
    title: 'Umrago Guide to Perform Umrah - Part 1',
    category: 'TV Shows',
    thumbnail: thumb1,
    videoUrl: 'https://drive.google.com/file/d/1lAKfIOz_DvZTmTuJBmu97n8sMhQqDPz1/preview',
    client: 'Bewide Technology',
    description: 'Umrah guide segment focused on key steps and preparation.',
    tools: ['Adobe Premiere Pro', 'CapCut'],
  },
  {
    id: 15,
    title: 'Umrago Guide to Perform Umrah - Part 2',
    category: 'TV Shows',
    thumbnail: thumb1,
    videoUrl: 'https://drive.google.com/file/d/1ksCdRJcLDS10Sz_LLcuB7Ax0hgNPTXXY/preview',
    client: 'Bewide Technology',
    description: 'Continuation of the Umrah walkthrough with pacing for clarity.',
    tools: ['Adobe Premiere Pro', 'CapCut'],
  },
  {
    id: 16,
    title: 'Umrago Guide to Perform Umrah - Part 3',
    category: 'TV Shows',
    thumbnail: thumb1,
    videoUrl: 'https://drive.google.com/file/d/1zYuqZsfMzFJu9MxjOqr7DHUDVTedSUb7/preview',
    client: 'Bewide Technology',
    description: 'Guided segment emphasizing smooth transitions and VO balance.',
    tools: ['Adobe Premiere Pro', 'CapCut'],
  },
  {
    id: 17,
    title: 'Umrago Guide to Perform Umrah - Part 4',
    category: 'TV Shows',
    thumbnail: thumb1,
    videoUrl: 'https://drive.google.com/file/d/1PymZ7Uc9QeIxtQ2L04Selynr3cKmRe6j/preview',
    client: 'Bewide Technology',
    description: 'Closing segment covering final steps and takeaways.',
    tools: ['Adobe Premiere Pro', 'CapCut'],
  },
  {
    id: 1,
    title: 'Africa TV-Shows Series',
    category: 'TV Shows',
    thumbnail: thumb1,
    videoUrl: 'https://drive.google.com/file/d/1SHloUL30NHICOHxGbPinrvnY2IlyeLpi/preview',
    client: 'Africa TV',
    description: 'Lead editor for a 4-part documentary series focusing on urban development.',
    tools: ['Premiere Pro', 'After Effects','Cap cut'],
  },
  {
    id: 2,
    title: 'TV Show Feature - Segment 1',
    category: 'Commercials',
    thumbnail: 'https://img.youtube.com/vi/cypaXfMVFb4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/cypaXfMVFb4',
    client: 'Broadcast',
    description: 'Segment edit focusing on pacing and broadcast polish.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 3,
    title: 'Startup Launch Promo',
    category: 'Promotional',
    thumbnail: thumb3,
    videoUrl: 'https://www.youtube.com/embed/jNQXAC9IVRw',
    client: 'TechHub',
    description: 'Explainer video and hype reel for a new fintech startup.',
    tools: ['After Effects', 'Illustrator'],
  },
  {
    id: 4,
    title: 'Marathon Highlights',
    category: 'Sports',
    thumbnail: thumb4,
    videoUrl: 'https://www.youtube.com/embed/HhFmvJ2i_gY',
    client: 'Addis Sports',
    description: 'Fast-paced highlight reel capturing the emotion of the race.',
    tools: ['Premiere Pro', 'SpeedGrade'],
  },
  {
    id: 5,
    title: 'Fashion Week Reels',
    category: 'Social Media',
    thumbnail: thumb5,
    videoUrl: 'https://www.youtube.com/embed/EngW7tLk6R8',
    client: 'Vogue Local',
    description: 'Vertical short-form content optimized for Instagram and TikTok.',
    tools: ['CapCut', 'Premiere Pro'],
  },
  {
    id: 6,
    title: 'Corporate Annual Report',
    category: 'Promotional',
    thumbnail: thumb6,
    videoUrl: 'https://www.youtube.com/embed/ysz5S6P_8-k',
    client: 'Bank of Abyssinia',
    description: 'Professional corporate communication video combining interviews and b-roll.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 7,
    title: 'Indehsab Podcast - Episode 8',
    category: 'Podcast',
    thumbnail: 'https://img.youtube.com/vi/LGGqWkstB8A/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/LGGqWkstB8A?list=PLX8Zwu8kixtKE0F-8TtSbPSqKP3lDooSE',
    client: 'Africa TV',
    description: 'Podcast episode edit with polished audio mix and pacing for broadcast.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 8,
    title: 'Indehsab Podcast - Episode 9',
    category: 'Podcast',
    thumbnail: 'https://img.youtube.com/vi/fxvkRz7pn8w/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/fxvkRz7pn8w?list=PLX8Zwu8kixtKE0F-8TtSbPSqKP3lDooSE',
    client: 'Africa TV',
    description: 'Podcast episode cut with dialogue clean-up and supporting visuals.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 9,
    title: 'Indehsab Podcast - Episode 2',
    category: 'Podcast',
    thumbnail: 'https://img.youtube.com/vi/2PjJOTaDuYo/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/2PjJOTaDuYo?list=PLX8Zwu8kixtKE0F-8TtSbPSqKP3lDooSE',
    client: 'Africa TV',
    description: 'Podcast storytelling focused on clear narration and rhythm.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 10,
    title: 'Indehsab Podcast - Episode 4',
    category: 'Podcast',
    thumbnail: 'https://img.youtube.com/vi/FjBIf0-Tdgg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/FjBIf0-Tdgg?list=PLX8Zwu8kixtKE0F-8TtSbPSqKP3lDooSE',
    client: 'Africa TV',
    description: 'Podcast mix balancing interviews, beds, and transitions.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 11,
    title: 'TV Show Feature - Segment 2',
    category: 'Commercials',
    thumbnail: 'https://img.youtube.com/vi/Ai4qR2PxiMQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/Ai4qR2PxiMQ',
    client: 'Broadcast',
    description: 'Cut delivering narrative clarity with tight dialogue edits.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 12,
    title: 'TV Show Feature - Segment 3',
    category: 'Commercials',
    thumbnail: 'https://img.youtube.com/vi/HFgPr6_XfUQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/HFgPr6_XfUQ',
    client: 'Broadcast',
    description: 'Segment emphasizing emotional beats and smooth transitions.',
    tools: ['Premiere Pro', 'Audition'],
  },
  {
    id: 13,
    title: 'TV Show Feature - Segment 4',
    category: 'Commercials',
    thumbnail: 'https://img.youtube.com/vi/I9m2kad58pI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/embed/I9m2kad58pI',
    client: 'Broadcast',
    description: 'Broadcast-ready edit balancing VO, beds, and pacing.',
    tools: ['Premiere Pro', 'Audition'],
  },
];

export const SERVICES: Service[] = [
  {
    id: 1,
    title: 'Video Editing',
    description: 'Professional cutting, pacing, and storytelling for TV, web, and film.',
    iconName: 'Scissors',
  },
  {
    id: 2,
    title: 'Color Grading',
    description: 'Cinematic color correction to set the perfect mood and tone.',
    iconName: 'Wand2',
  },
  {
    id: 3,
    title: 'Motion Graphics',
    description: 'Dynamic text animations, lower thirds, and intro sequences.',
    iconName: 'MonitorPlay',
  },
  {
    id: 4,
    title: 'YouTube Production',
    description: 'End-to-end post-production for high-retention YouTube content.',
    iconName: 'Youtube',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: 'Abdulaziz Mudawi',
    role: 'Producer, Africa TV',
    quote:
      "Faysal has an incredible eye for detail. He doesn't just cut footage; he builds a narrative that keeps viewers hooked.",
  },
  {
    id: 2,
    name: 'Abdulahkim Nasir',
    role: 'Marketing Director,MSL',
    quote: 'Fast, reliable, and extremely creative. The promotional video he made for us doubled our engagement rates.',
  },
  {
    id: 3,
    name: 'Aymen muhammedzayn',
    role: 'Socialmedia manager, Africa TV',
    quote: 'His color grading transformed my flat footage into a cinematic masterpiece. Highly recommended.',
  },
];

export const SKILL_DATA: SkillData[] = [
  {
    subject: 'Storytelling',
    A: 95,
    fullMark: 100,
    description: 'Crafting compelling narratives that keep the audience engaged from start to finish.',
  },
  {
    subject: 'Color Grading',
    A: 85,
    fullMark: 100,
    description: 'Enhancing the mood and tone of footage using DaVinci Resolve and Lumetri.',
  },
  {
    subject: 'Motion Gfx',
    A: 75,
    fullMark: 100,
    description: 'Creating dynamic text animations and lower thirds in After Effects.',
  },
  {
    subject: 'Sound Design',
    A: 80,
    fullMark: 100,
    description: 'Layering SFX and mixing audio for an immersive experience.',
  },
  {
    subject: 'Pacing',
    A: 90,
    fullMark: 100,
    description: 'Mastering the rhythm of the edit to evoke the right emotion.',
  },
  {
    subject: 'Software',
    A: 95,
    fullMark: 100,
    description: 'Expert proficiency in Premiere Pro, CapCut, and Adobe Suite.',
  },
];

export const EXPERIENCES: ExperienceItem[] = [
  {
    id: 1,
    title: 'Freelance Video Editor',
    company: 'Independent',
    period: 'Jan 2022 - Present',
    highlights: [
      'Produced engaging video content for diverse clients: promotional videos, event coverage, TV programs, and YouTube content',
      'Edited raw footage into compelling narratives aligned with client branding and messaging',
      'Specialized in interview editing with smooth transitions and captivating storytelling while meeting deadlines and budgets',
      'Continuously updated skills and stayed informed on latest video editing trends and technologies',
      'Flexible and adaptable to changing project requirements and timelines',
    ],
  },
  {
    id: 2,
    title: 'Video Editor & Assistant Camera Operator',
    company: 'Africa TV1',
    period: '2024 - 2025',
    highlights: [
      'Collaborated with production teams to edit and assemble raw footage into engaging content',
      'Assisted with camera operation and setup during shoots and live broadcasts',
      'Contributed creative ideas to enhance overall production quality',
    ],
  },
  {
    id: 3,
    title: 'Volunteer Video Editor & Graphic Designer',
    company: 'MS League',
    period: '2023 - 2024',
    highlights: [
      'Created promotional materials and edited event coverage as a volunteer',
      'Supported community initiatives with visual communication assets',
    ],
  },
  {
    id: 4,
    title: 'Video Editor',
    company: 'Allcan Development Center',
    period: '2024',
    highlights: [
      'Edited educational and organizational content to support training and outreach',
      'Delivered on tight deadlines while maintaining quality standards',
    ],
  },
];

export const EDUCATION: EducationItem[] = [
  {
    id: 1,
    program: 'BSc in Information Science',
    institution: 'Addis Ababa University',
    period: '2021 - 2025 (expected)',
    details: [
      'Built foundations in information systems, digital media, and communication',
      'Applied principles to video production workflows and asset management',
    ],
  },
  {
    id: 2,
    program: 'Videography & Editing Certification',
    institution: 'Bilalul Habashi Center',
    period: '2024',
    details: [
      'Training in camera operations, editing workflows, and post-production techniques',
    ],
  },
  {
    id: 3,
    program: 'Leadership & Islamic Studies',
    institution: 'Risala Center for Youth Empowerment',
    period: '2022 - 2026 (in progress)',
    details: [
      'Certification focused on leadership, community service, and ethics',
    ],
  },
];

export const CERTIFICATIONS: CertificationItem[] = [
  {
    id: 1,
    year: '2024',
    title: 'Video Editing Certifications',
    issuer: 'Udemy',
  },
  {
    id: 2,
    year: '2024',
    title: 'Videography & Editing Certification',
    issuer: 'Bilalul Habashi Center',
  },
];